class Stack<T> {
  private items: T[] = [];

  push(item: T): void {
    this.items.push(item);
  }

  pop(): T | undefined {
    return this.items.pop();
  }

  popByIndex(index: number): T | undefined {
    if (index < 0 || index >= this.items.length) {
      return undefined;
    }
    
    return this.items.splice(index, 1)[0];
  }

  peek(): T {
    return this.items[this.items.length - 1];
  }

  isEmpty(): boolean {
    return this.items.length === 0;
  }

  size(): number {
    return this.items.length;
  }
}

const movements = [
  { move: 2, from: 8, to: 4 },
  { move: 2, from: 7, to: 3 },
  { move: 2, from: 9, to: 2 },
  { move: 4, from: 1, to: 9 },
  { move: 1, from: 7, to: 8 },
  { move: 1, from: 9, to: 6 },
  { move: 6, from: 6, to: 1 },
  { move: 6, from: 1, to: 6 },
  { move: 2, from: 7, to: 1 },
  { move: 9, from: 4, to: 1 },
  { move: 6, from: 2, to: 7 },
  { move: 5, from: 9, to: 7 },
  { move: 7, from: 3, to: 7 },
  { move: 19, from: 7, to: 9 },
  { move: 1, from: 7, to: 1 },
  { move: 3, from: 6, to: 8 },
  { move: 4, from: 5, to: 6 },
  { move: 1, from: 4, to: 1 },
  { move: 2, from: 5, to: 2 },
  { move: 8, from: 9, to: 7 },
  { move: 1, from: 5, to: 1 },
  { move: 3, from: 9, to: 4 },
  { move: 1, from: 4, to: 9 },
  { move: 2, from: 4, to: 7 },
  { move: 1, from: 7, to: 6 },
  { move: 3, from: 8, to: 9 },
  { move: 17, from: 1, to: 7 },
  { move: 21, from: 7, to: 3 },
  { move: 4, from: 6, to: 2 },
  { move: 1, from: 7, to: 2 },
  { move: 8, from: 9, to: 2 },
  { move: 2, from: 8, to: 3 },
  { move: 1, from: 1, to: 7 },
  { move: 2, from: 7, to: 9 },
  { move: 1, from: 6, to: 1 },
  { move: 1, from: 7, to: 4 },
  { move: 1, from: 1, to: 2 },
  { move: 4, from: 6, to: 1 },
  { move: 1, from: 9, to: 2 },
  { move: 1, from: 7, to: 9 },
  { move: 1, from: 4, to: 1 },
  { move: 7, from: 3, to: 7 },
  { move: 6, from: 2, to: 8 },
  { move: 3, from: 3, to: 4 },
  { move: 1, from: 8, to: 4 },
  { move: 12, from: 2, to: 8 },
  { move: 2, from: 9, to: 2 },
  { move: 12, from: 3, to: 2 },
  { move: 12, from: 8, to: 6 },
  { move: 3, from: 4, to: 2 },
  { move: 19, from: 2, to: 8 },
  { move: 4, from: 1, to: 9 },
  { move: 1, from: 3, to: 8 },
  { move: 1, from: 4, to: 6 },
  { move: 1, from: 2, to: 4 },
  { move: 1, from: 6, to: 3 },
  { move: 8, from: 9, to: 6 },
  { move: 1, from: 4, to: 9 },
  { move: 1, from: 3, to: 1 },
  { move: 1, from: 9, to: 5 },
  { move: 11, from: 6, to: 3 },
  { move: 5, from: 8, to: 6 },
  { move: 14, from: 6, to: 9 },
  { move: 2, from: 1, to: 4 },
  { move: 3, from: 8, to: 1 },
  { move: 8, from: 8, to: 4 },
  { move: 3, from: 3, to: 4 },
  { move: 8, from: 3, to: 1 },
  { move: 9, from: 8, to: 2 },
  { move: 12, from: 4, to: 2 },
  { move: 12, from: 9, to: 3 },
  { move: 9, from: 3, to: 4 },
  { move: 1, from: 5, to: 3 },
  { move: 7, from: 7, to: 1 },
  { move: 2, from: 9, to: 1 },
  { move: 2, from: 4, to: 6 },
  { move: 16, from: 2, to: 6 },
  { move: 1, from: 2, to: 8 },
  { move: 10, from: 1, to: 4 },
  { move: 1, from: 8, to: 2 },
  { move: 4, from: 1, to: 6 },
  { move: 15, from: 4, to: 8 },
  { move: 1, from: 4, to: 2 },
  { move: 2, from: 6, to: 8 },
  { move: 5, from: 2, to: 8 },
  { move: 21, from: 8, to: 3 },
  { move: 6, from: 1, to: 3 },
  { move: 15, from: 6, to: 1 },
  { move: 1, from: 2, to: 1 },
  { move: 1, from: 8, to: 9 },
  { move: 15, from: 1, to: 3 },
  { move: 7, from: 3, to: 8 },
  { move: 1, from: 7, to: 9 },
  { move: 2, from: 9, to: 8 },
  { move: 2, from: 3, to: 7 },
  { move: 4, from: 6, to: 1 },
  { move: 2, from: 7, to: 8 },
  { move: 1, from: 6, to: 2 },
  { move: 4, from: 8, to: 3 },
  { move: 2, from: 4, to: 8 },
  { move: 1, from: 2, to: 1 },
  { move: 4, from: 1, to: 5 },
  { move: 3, from: 5, to: 8 },
  { move: 1, from: 5, to: 1 },
  { move: 12, from: 8, to: 3 },
  { move: 3, from: 1, to: 2 },
  { move: 17, from: 3, to: 5 },
  { move: 2, from: 5, to: 3 },
  { move: 15, from: 5, to: 1 },
  { move: 1, from: 1, to: 4 },
  { move: 17, from: 3, to: 2 },
  { move: 5, from: 2, to: 8 },
  { move: 17, from: 3, to: 6 },
  { move: 6, from: 1, to: 3 },
  { move: 5, from: 1, to: 6 },
  { move: 4, from: 8, to: 9 },
  { move: 10, from: 3, to: 8 },
  { move: 7, from: 2, to: 9 },
  { move: 2, from: 6, to: 3 },
  { move: 2, from: 2, to: 8 },
  { move: 1, from: 1, to: 4 },
  { move: 17, from: 6, to: 9 },
  { move: 13, from: 8, to: 2 },
  { move: 2, from: 4, to: 1 },
  { move: 1, from: 6, to: 7 },
  { move: 2, from: 2, to: 4 },
  { move: 8, from: 2, to: 7 },
  { move: 1, from: 6, to: 1 },
  { move: 4, from: 7, to: 9 },
  { move: 1, from: 4, to: 7 },
  { move: 1, from: 4, to: 6 },
  { move: 1, from: 1, to: 7 },
  { move: 5, from: 2, to: 4 },
  { move: 2, from: 3, to: 8 },
  { move: 6, from: 7, to: 1 },
  { move: 1, from: 7, to: 4 },
  { move: 11, from: 9, to: 7 },
  { move: 1, from: 8, to: 4 },
  { move: 8, from: 1, to: 2 },
  { move: 1, from: 1, to: 4 },
  { move: 1, from: 1, to: 9 },
  { move: 1, from: 6, to: 1 },
  { move: 1, from: 8, to: 4 },
  { move: 6, from: 2, to: 3 },
  { move: 1, from: 1, to: 3 },
  { move: 1, from: 6, to: 7 },
  { move: 1, from: 4, to: 6 },
  { move: 6, from: 2, to: 5 },
  { move: 7, from: 3, to: 4 },
  { move: 2, from: 7, to: 6 },
  { move: 2, from: 7, to: 3 },
  { move: 8, from: 7, to: 5 },
  { move: 3, from: 6, to: 7 },
  { move: 1, from: 5, to: 7 },
  { move: 1, from: 7, to: 5 },
  { move: 13, from: 9, to: 3 },
  { move: 1, from: 3, to: 8 },
  { move: 8, from: 4, to: 3 },
  { move: 3, from: 5, to: 1 },
  { move: 7, from: 4, to: 1 },
  { move: 5, from: 1, to: 4 },
  { move: 3, from: 1, to: 4 },
  { move: 2, from: 1, to: 8 },
  { move: 2, from: 7, to: 5 },
  { move: 2, from: 8, to: 9 },
  { move: 1, from: 7, to: 6 },
  { move: 1, from: 8, to: 7 },
  { move: 4, from: 5, to: 1 },
  { move: 1, from: 7, to: 2 },
  { move: 2, from: 1, to: 8 },
  { move: 1, from: 2, to: 1 },
  { move: 5, from: 9, to: 7 },
  { move: 3, from: 9, to: 4 },
  { move: 8, from: 4, to: 8 },
  { move: 6, from: 8, to: 5 },
  { move: 11, from: 5, to: 1 },
  { move: 3, from: 4, to: 2 },
  { move: 9, from: 3, to: 7 },
  { move: 6, from: 7, to: 2 },
  { move: 13, from: 3, to: 2 },
  { move: 3, from: 8, to: 1 },
  { move: 2, from: 2, to: 8 },
  { move: 1, from: 6, to: 7 },
  { move: 3, from: 8, to: 4 },
  { move: 9, from: 1, to: 5 },
  { move: 5, from: 5, to: 8 },
  { move: 2, from: 8, to: 4 },
  { move: 3, from: 9, to: 4 },
  { move: 2, from: 8, to: 2 },
  { move: 8, from: 1, to: 5 },
  { move: 8, from: 7, to: 9 },
  { move: 1, from: 8, to: 3 },
  { move: 15, from: 5, to: 9 },
  { move: 6, from: 4, to: 1 },
  { move: 1, from: 7, to: 2 },
  { move: 4, from: 2, to: 1 },
  { move: 1, from: 3, to: 4 },
  { move: 5, from: 1, to: 7 },
  { move: 3, from: 7, to: 3 },
  { move: 14, from: 9, to: 8 },
  { move: 1, from: 4, to: 8 },
  { move: 1, from: 7, to: 6 },
  { move: 2, from: 4, to: 5 },
  { move: 4, from: 1, to: 5 },
  { move: 1, from: 6, to: 5 },
  { move: 4, from: 9, to: 3 },
  { move: 5, from: 3, to: 7 },
  { move: 4, from: 5, to: 9 },
  { move: 1, from: 3, to: 7 },
  { move: 1, from: 3, to: 2 },
  { move: 4, from: 5, to: 2 },
  { move: 4, from: 7, to: 5 },
  { move: 4, from: 2, to: 1 },
  { move: 1, from: 5, to: 4 },
  { move: 7, from: 9, to: 7 },
  { move: 1, from: 4, to: 2 },
  { move: 1, from: 5, to: 8 },
  { move: 21, from: 2, to: 4 },
  { move: 1, from: 9, to: 8 },
  { move: 1, from: 9, to: 4 },
  { move: 3, from: 4, to: 1 },
  { move: 7, from: 1, to: 6 },
  { move: 1, from: 5, to: 1 },
  { move: 18, from: 4, to: 7 },
  { move: 1, from: 5, to: 8 },
  { move: 27, from: 7, to: 8 },
  { move: 1, from: 7, to: 3 },
  { move: 1, from: 3, to: 7 },
  { move: 1, from: 7, to: 2 },
  { move: 1, from: 2, to: 1 },
  { move: 42, from: 8, to: 9 },
  { move: 1, from: 8, to: 7 },
  { move: 1, from: 8, to: 2 },
  { move: 1, from: 4, to: 6 },
  { move: 1, from: 2, to: 9 },
  { move: 2, from: 1, to: 2 },
  { move: 1, from: 7, to: 3 },
  { move: 7, from: 6, to: 4 },
  { move: 4, from: 9, to: 6 },
  { move: 1, from: 3, to: 2 },
  { move: 1, from: 2, to: 7 },
  { move: 2, from: 2, to: 5 },
  { move: 1, from: 8, to: 4 },
  { move: 1, from: 9, to: 3 },
  { move: 5, from: 4, to: 7 },
  { move: 1, from: 5, to: 6 },
  { move: 1, from: 5, to: 9 },
  { move: 1, from: 6, to: 3 },
  { move: 1, from: 7, to: 5 },
  { move: 2, from: 3, to: 2 },
  { move: 22, from: 9, to: 7 },
  { move: 2, from: 2, to: 3 },
  { move: 18, from: 7, to: 9 },
  { move: 1, from: 4, to: 9 },
  { move: 1, from: 1, to: 4 },
  { move: 4, from: 7, to: 3 },
  { move: 4, from: 3, to: 2 },
  { move: 3, from: 4, to: 5 },
  { move: 1, from: 2, to: 4 },
  { move: 5, from: 6, to: 9 },
  { move: 1, from: 5, to: 3 },
  { move: 1, from: 4, to: 7 },
  { move: 2, from: 5, to: 1 },
  { move: 3, from: 2, to: 4 },
  { move: 1, from: 5, to: 6 },
  { move: 2, from: 7, to: 9 },
  { move: 1, from: 6, to: 8 },
  { move: 2, from: 3, to: 2 },
  { move: 2, from: 4, to: 7 },
  { move: 1, from: 8, to: 7 },
  { move: 1, from: 4, to: 6 },
  { move: 35, from: 9, to: 7 },
  { move: 13, from: 7, to: 3 },
  { move: 1, from: 2, to: 7 },
  { move: 1, from: 2, to: 5 },
  { move: 1, from: 5, to: 8 },
  { move: 1, from: 8, to: 5 },
  { move: 8, from: 7, to: 3 },
  { move: 1, from: 6, to: 4 },
  { move: 6, from: 3, to: 9 },
  { move: 1, from: 1, to: 9 },
  { move: 1, from: 4, to: 1 },
  { move: 14, from: 9, to: 8 },
  { move: 1, from: 5, to: 7 },
  { move: 16, from: 3, to: 2 },
  { move: 2, from: 1, to: 2 },
  { move: 1, from: 9, to: 2 },
  { move: 1, from: 8, to: 1 },
  { move: 1, from: 1, to: 3 },
  { move: 7, from: 2, to: 9 },
  { move: 6, from: 9, to: 8 },
  { move: 1, from: 3, to: 4 },
  { move: 3, from: 7, to: 6 },
  { move: 2, from: 2, to: 1 },
  { move: 1, from: 4, to: 7 },
  { move: 2, from: 2, to: 5 },
  { move: 1, from: 9, to: 6 },
  { move: 2, from: 2, to: 5 },
  { move: 2, from: 6, to: 2 },
  { move: 4, from: 5, to: 4 },
  { move: 5, from: 2, to: 6 },
  { move: 1, from: 1, to: 7 },
  { move: 1, from: 1, to: 2 },
  { move: 13, from: 8, to: 1 },
  { move: 2, from: 8, to: 4 },
  { move: 19, from: 7, to: 4 },
  { move: 3, from: 1, to: 6 },
  { move: 11, from: 4, to: 3 },
  { move: 2, from: 7, to: 9 },
  { move: 4, from: 2, to: 5 },
  { move: 2, from: 9, to: 5 },
  { move: 1, from: 7, to: 4 },
  { move: 2, from: 5, to: 7 },
  { move: 4, from: 3, to: 4 },
  { move: 3, from: 4, to: 1 },
  { move: 3, from: 5, to: 1 },
  { move: 9, from: 6, to: 4 },
  { move: 1, from: 7, to: 9 },
  { move: 1, from: 7, to: 5 },
  { move: 10, from: 1, to: 4 },
  { move: 1, from: 9, to: 6 },
  { move: 1, from: 6, to: 8 },
  { move: 32, from: 4, to: 5 },
  { move: 7, from: 5, to: 4 },
  { move: 27, from: 5, to: 9 },
  { move: 5, from: 3, to: 2 },
  { move: 3, from: 2, to: 8 },
  { move: 1, from: 6, to: 2 },
  { move: 8, from: 4, to: 9 },
  { move: 1, from: 2, to: 9 },
  { move: 8, from: 8, to: 6 },
  { move: 2, from: 4, to: 3 },
  { move: 1, from: 2, to: 3 },
  { move: 15, from: 9, to: 8 },
  { move: 4, from: 1, to: 4 },
  { move: 3, from: 4, to: 8 },
  { move: 6, from: 9, to: 7 },
  { move: 1, from: 4, to: 9 },
  { move: 8, from: 8, to: 2 },
  { move: 2, from: 1, to: 9 },
  { move: 2, from: 7, to: 9 },
  { move: 10, from: 8, to: 3 },
  { move: 6, from: 2, to: 6 },
  { move: 2, from: 3, to: 2 },
  { move: 6, from: 6, to: 3 },
  { move: 1, from: 7, to: 5 },
  { move: 8, from: 3, to: 2 },
  { move: 4, from: 3, to: 2 },
  { move: 1, from: 3, to: 5 },
  { move: 6, from: 6, to: 1 },
  { move: 4, from: 3, to: 7 },
  { move: 2, from: 5, to: 8 },
  { move: 3, from: 7, to: 5 },
  { move: 6, from: 1, to: 7 },
  { move: 1, from: 3, to: 4 },
  { move: 1, from: 3, to: 9 },
  { move: 10, from: 7, to: 4 },
  { move: 8, from: 2, to: 8 },
  { move: 11, from: 9, to: 5 },
  { move: 11, from: 4, to: 1 },
  { move: 5, from: 2, to: 6 },
  { move: 3, from: 2, to: 7 },
  { move: 11, from: 1, to: 6 },
  { move: 1, from: 5, to: 6 },
  { move: 8, from: 5, to: 4 },
  { move: 19, from: 6, to: 7 },
  { move: 3, from: 7, to: 9 },
  { move: 3, from: 5, to: 4 },
  { move: 1, from: 2, to: 5 },
  { move: 3, from: 5, to: 7 },
  { move: 8, from: 9, to: 6 },
  { move: 2, from: 4, to: 1 },
  { move: 1, from: 1, to: 9 },
  { move: 2, from: 9, to: 7 },
  { move: 6, from: 6, to: 2 },
  { move: 2, from: 4, to: 6 },
  { move: 4, from: 8, to: 6 },
  { move: 1, from: 8, to: 1 },
  { move: 7, from: 6, to: 7 },
  { move: 1, from: 9, to: 4 },
  { move: 5, from: 8, to: 4 },
  { move: 3, from: 2, to: 6 },
  { move: 4, from: 6, to: 4 },
  { move: 2, from: 9, to: 6 },
  { move: 3, from: 2, to: 9 },
  { move: 16, from: 4, to: 8 },
  { move: 1, from: 6, to: 8 },
  { move: 2, from: 9, to: 5 },
  { move: 1, from: 9, to: 7 },
  { move: 2, from: 5, to: 2 },
  { move: 1, from: 4, to: 6 },
  { move: 2, from: 2, to: 5 },
  { move: 1, from: 9, to: 6 },
  { move: 3, from: 7, to: 3 },
  { move: 7, from: 7, to: 8 },
  { move: 2, from: 7, to: 1 },
  { move: 3, from: 8, to: 5 },
  { move: 3, from: 6, to: 2 },
  { move: 4, from: 7, to: 4 },
  { move: 1, from: 5, to: 1 },
  { move: 1, from: 5, to: 7 },
  { move: 3, from: 3, to: 4 },
  { move: 5, from: 1, to: 4 },
  { move: 16, from: 7, to: 2 },
  { move: 5, from: 4, to: 7 },
  { move: 19, from: 8, to: 1 },
  { move: 11, from: 2, to: 9 },
  { move: 11, from: 9, to: 6 },
  { move: 2, from: 1, to: 6 },
  { move: 2, from: 4, to: 1 },
  { move: 5, from: 4, to: 6 },
  { move: 1, from: 5, to: 9 },
  { move: 1, from: 9, to: 6 },
  { move: 2, from: 2, to: 6 },
  { move: 1, from: 5, to: 4 },
  { move: 8, from: 6, to: 5 },
  { move: 16, from: 1, to: 6 },
  { move: 1, from: 4, to: 9 },
  { move: 3, from: 2, to: 9 },
  { move: 2, from: 2, to: 5 },
  { move: 2, from: 5, to: 8 },
  { move: 4, from: 8, to: 4 },
  { move: 4, from: 9, to: 7 },
  { move: 2, from: 1, to: 3 },
  { move: 5, from: 6, to: 4 },
  { move: 21, from: 6, to: 2 },
  { move: 9, from: 7, to: 3 },
  { move: 1, from: 1, to: 2 },
  { move: 1, from: 5, to: 3 },
  { move: 23, from: 2, to: 7 },
  { move: 1, from: 7, to: 5 },
  { move: 3, from: 6, to: 1 },
  { move: 9, from: 4, to: 5 },
  { move: 11, from: 7, to: 1 },
  { move: 2, from: 3, to: 4 },
  { move: 1, from: 3, to: 7 },
  { move: 1, from: 4, to: 1 },
  { move: 10, from: 1, to: 6 },
  { move: 5, from: 7, to: 1 },
  { move: 3, from: 1, to: 4 },
  { move: 7, from: 1, to: 7 },
  { move: 4, from: 3, to: 8 },
  { move: 4, from: 7, to: 4 },
  { move: 5, from: 7, to: 3 },
  { move: 2, from: 4, to: 9 },
  { move: 1, from: 8, to: 1 },
  { move: 4, from: 4, to: 1 },
  { move: 1, from: 6, to: 1 },
  { move: 1, from: 6, to: 5 },
  { move: 16, from: 5, to: 1 },
  { move: 2, from: 5, to: 7 },
  { move: 1, from: 5, to: 6 },
  { move: 2, from: 8, to: 2 },
  { move: 1, from: 7, to: 9 },
  { move: 3, from: 9, to: 5 },
  { move: 2, from: 5, to: 4 },
  { move: 6, from: 7, to: 1 },
  { move: 3, from: 4, to: 7 },
  { move: 1, from: 8, to: 6 },
  { move: 5, from: 1, to: 4 },
  { move: 1, from: 6, to: 1 },
  { move: 19, from: 1, to: 5 },
  { move: 1, from: 7, to: 6 },
  { move: 9, from: 3, to: 1 },
  { move: 6, from: 6, to: 5 },
  { move: 4, from: 6, to: 9 },
  { move: 3, from: 9, to: 4 },
  { move: 13, from: 1, to: 4 },
  { move: 1, from: 3, to: 1 },
  { move: 2, from: 5, to: 1 },
  { move: 1, from: 2, to: 3 },
  { move: 1, from: 3, to: 9 },
  { move: 4, from: 5, to: 4 },
  { move: 1, from: 2, to: 3 },
  { move: 1, from: 3, to: 5 },
  { move: 1, from: 9, to: 1 },
  { move: 1, from: 9, to: 5 },
  { move: 19, from: 4, to: 7 },
  { move: 4, from: 1, to: 6 },
  { move: 5, from: 4, to: 3 },
  { move: 3, from: 6, to: 1 },
  { move: 1, from: 6, to: 8 },
  { move: 2, from: 1, to: 6 },
  { move: 2, from: 1, to: 7 },
  { move: 2, from: 6, to: 3 },
  { move: 2, from: 3, to: 1 },
  { move: 8, from: 7, to: 6 },
  { move: 5, from: 3, to: 9 },
  { move: 2, from: 4, to: 9 },
  { move: 2, from: 6, to: 8 },
  { move: 10, from: 7, to: 2 },
  { move: 7, from: 2, to: 9 },
  { move: 1, from: 8, to: 9 },
  { move: 1, from: 1, to: 2 },
  { move: 2, from: 9, to: 3 },
  { move: 2, from: 8, to: 7 },
  { move: 1, from: 1, to: 6 },
  { move: 1, from: 2, to: 8 },
  { move: 2, from: 2, to: 5 },
  { move: 4, from: 5, to: 7 },
  { move: 5, from: 6, to: 1 },
  { move: 1, from: 3, to: 4 },
];

const stacksRepresentation = [
  ["V", "C", "D", "R", "Z", "G", "B", "W"],
  ["G", "W", "F", "C", "B", "S", "T", "V"],
  ["C", "B", "S", "N", "N"],
  ["Q", "G", "M", "N", "J", "V", "C", "P"],
  ["T", "S", "L", "F", "D", "H", "B"],
  ["J", "V", "T", "W", "M", "N"],
  ["P", "F", "L", "C", "S", "T", "G"],
  ["B", "D", "Z"],
  ["M", "N", "Z", "W"]
]

const addStacksToStackClass = (stacksArray: string[][]): Record<number, Stack<string>> => {
  const stacks: Record<number, Stack<string>> = {};

  for (let i = 0; i < stacksArray.length; i++) {
    stacks[i + 1] = new Stack();
    for (let j = 0; j < stacksArray[i].length; j++) {
      stacks[i + 1]?.push(stacksArray[i][j]);
    }
  }

  return stacks;
}

const getPeeksOfStacksConcatinatedString = (stacks: Record<number, Stack<string>>): string => {
  let peeksOfStacks = '';

  for (let stackNumber in stacks) {
    peeksOfStacks += stacks[stackNumber].peek();
  }

  return peeksOfStacks;
}

const getPeeksOfStacks = (movements: {move: number, from: number, to: number}[]): string => {
  const stacks: Record<number, Stack<string>> = addStacksToStackClass(stacksRepresentation);

  for (let movement of movements) {
    for (let i = 0; i < movement.move; i++) {
      const popedCrate = stacks[movement.from].pop();
      stacks[movement.to].push(popedCrate as string);
    }
  }

  return getPeeksOfStacksConcatinatedString(stacks);
}

const getPeeksOfStacksForCrateMover9001 = (movements: {move: number, from: number, to: number}[]): string => {
  const stacks: Record<number, Stack<string>> = addStacksToStackClass(stacksRepresentation);

  for (let movement of movements) {
    for (let i = 0; i < movement.move; i++) {
      if (movement.move === 1) {
        const popedCrate = stacks[movement.from].pop();
        stacks[movement.to].push(popedCrate as string);
      } else {
        let startingIndex = stacks[movement.from].size() - (movement.move - i);
        const popedCrate = stacks[movement.from].popByIndex(startingIndex);
        stacks[movement.to].push(popedCrate as string);
      }
    }
  }

  return getPeeksOfStacksConcatinatedString(stacks);
}